services:
  - type: web
    name: oriente-backend
    env: python
    region: oregon
    plan: free
    branch: main
    rootDirectory: oriente-backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn app.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_EXPIRATION_MINUTES
        value: 1440
      - key: SERVER_HOST
        value: 0.0.0.0
      - key: SERVER_PORT
        fromGroup: web
      - key: CORS_ORIGINS
        value: https://apporiente.vercel.app,http://localhost:5173,http://localhost:3000
      - key: APP_NAME
        value: Oriente Backend
      - key: APP_VERSION
        value: 0.0.1
      - key: DEBUG
        value: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
